name: Build Project

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x

    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Build
      env: 
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        Bundle: True
      run: |
        dotnet restore src/BootstrapBlazor --no-cache
        dotnet build src/BootstrapBlazor
